org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true
org.gradle.configuration-cache=false

# Fabric Properties
minecraft_version=26.2
loader_version=0.19.3
loom_version=1.17-SNAPSHOT

# Mod Properties
mod_version=0.9.0
maven_group=net.cinchtail.cinchssandycatacombs
mod_id=cinchssandycatacombs
mod_name=Cinch's Lost Mob Grinders
mod_license=ARR
mod_authors=Cinchtail
mod_description=Adds a new large dungeons structures to deserts and makes sand farmable using husks and the new structure.

## Links
mod_homepage=https://www.curseforge.com/minecraft/mc-mods/cinchs-sandy-catacombs
mod_curseforge=https://www.curseforge.com/minecraft/mc-mods/cinchs-sandy-catacombs
mod_modrinth=https://modrinth.com/mod/cinchs-sandy-catacombs
mod_sources=https://github.com/cinchtail/Cinchs_Sandy_Catacombs
mod_discord=https://discord.gg/aBBz7E52Jy
mod_kofi=https://ko-fi.com/cinchtail
mod_youtube=https://www.youtube.com/@CinchPlaysMC

# Dependencies
fabric_api_version=0.152.2+26.2